all:
  hosts:
    pc:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

    # Example to add a new host
    # laptop:
      # ansible_host: laptop.home.arpa   # or an IP
      # ansible_user: youruser
      # ansible_ssh_private_key_file: ~/.ssh/id_ed25519  (optional)
      # ansible_python_interpreter: /usr/bin/python3     (often helpful)

  children:
    # Hardware profile: machines that should receive NVIDIA-specific packages/tasks
    nvidia:
      hosts:
        pc:
    # Usage profile: work-related tools/config should apply only to these machines
    work:
      hosts:
        pc:
    # Usage profile: development tools/config should apply only to these machines
    development:
      hosts:
        pc:
